### ISSUE TITLE
Char reach isn't 256 bits

### ISSUE THREAD

**Issue by karakchi** [jackwadden/graphgrep#1]
Hello Jack, 

I used graphgrep and hyperscan, it works fine with most ANMLZoo benchmarks. 
However, I got  "CHAR REACH ISNT 256 BITS! 10 Exiting..." with compiling graph of protomata, snort, Dotstar and PowerEn.

Do you have any idea about this error? 

Thanks, 
Rasha

**Comment by jackwadden** [comment]
I don't really maintain this code anymore. Please use the MNCaRT tool suite, hscompile and hsrun as I previously suggested.

-Jack
